version: '3.8'

# starts 8 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9008.
# They're set in two zones {1-4} and {5-8}.
services:
  minio1:
    image: minio/minio:latest
    volumes:
      - minio1:/data
    ports:
      - '9001:9000'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data http://minio{5...8}/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:latest
    volumes:
      - minio2:/data
    ports:
      - '9002:9000'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data http://minio{5...8}/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:latest
    volumes:
      - minio3:/data
    ports:
      - '9003:9000'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data http://minio{5...8}/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  nginx_proxy:
    image: nginx
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '9000:80'
    depends_on:
      - minio1
      - minio2
      - minio3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio1:
  minio2:
  minio3:
  minio4:
  minio5:
  minio6:
  minio7:
  minio8:
