version: "3.8"

services:
  restic:
    image: ajoergensen/rest-server:latest
    container_name: restic-server
    volumes:
      - ${RESTIC_DATA_PATH}/:/data
    ports:
      - "${RESTIC_PORT:-8000}:8000"
    restart: unless-stopped
