# https://taskfile.dev

version: '3'

vars:
  COMPOSE_PIHOLE_FILE: provision/compose/pihole.yml
  COMPOSE_TRAEFIK_FILE: provision/compose/traefik.yml
  COMPOSE_RESTIC_FILE: provision/compose/restic.yml
  COMPOSE_PORTAINER_FILE: provision/compose/portainer.yml
  COMPOSE_JELLYFIN_FILE: provision/compose/jellyfin.yml
  COMPOSE_QBITTORRENT_FILE: provision/compose/qbittorrent.yml

tasks:
  check:
    desc: Exist services and dependences
    run: once
    deps:
      - task: check:docker-compose

  check:docker-compose:
    desc: Exist docker-compose
    run: once
    preconditions:
      - sh: test "pipenv run command -v docker-compose"
        msg: 'Please Install docker-compose'

  service:
    desc: run command service
    run: once
    deps:
      - task: check
    cmds:
      - cmd: pipenv run docker-compose -f docker-compose.yml -f {{.COMPOSE_SERVICE_FILE}} {{.CLI_ARGS}}

  up:
    desc: up command service
    run: once
    deps:
      - task: check
    cmds:
      - cmd: pipenv run docker-compose -f docker-compose.yml -f {{.COMPOSE_SERVICE_FILE}} up -d --remove-orphans

  down:
    desc: down command service
    run: once
    deps:
      - task: check
    cmds:
      - cmd: pipenv run docker-compose -f docker-compose.yml -f {{.COMPOSE_SERVICE_FILE}} down

  pihole:
    desc: run service pihole using command
    run: once
    deps:
      - task: check
    cmds:
      - task: service
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/pihole.yml

  pihole:up:
    desc: run service pihole
    run: once
    deps:
      - task: check
    cmds:
      - task: up
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/pihole.yml

  pihole:down:
    desc: down service pihole
    run: once
    deps:
      - task: check
    cmds:
      - task: down
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/pihole.yml

  traefik:
    desc: run service traefik
    run: once
    deps:
      - task: check
    cmds:
      - task: service
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/traefik.yml

  traefik:up:
    desc: run service traefik
    run: once
    deps:
      - task: check
    cmds:
      - task: up
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/traefik.yml

  traefik:down:
    desc: down service traefik
    run: once
    deps:
      - task: check
    cmds:
      - task: down
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/traefik.yml

  portainer:
    desc: run service portainer
    run: once
    deps:
      - task: check
    cmds:
      - task: service
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/portainer.yml

  portainer:up:
    desc: run service portainer
    run: once
    deps:
      - task: check
    cmds:
      - task: up
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/portainer.yml

  portainer:down:
    desc: down service portainer
    run: once
    deps:
      - task: check
    cmds:
      - task: down
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/portainer.yml

  restic:
    desc: run service restic
    run: once
    deps:
      - task: check
    cmds:
      - task: service
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/restic.yml

  restic:up:
    desc: run service restic
    run: once
    deps:
      - task: check
    cmds:
      - task: up
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/restic.yml

  restic:down:
    desc: down service restic
    run: once
    deps:
      - task: check
    cmds:
      - task: down
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/restic.yml

  qbittorrent:
    desc: run service qbittorrent
    run: once
    deps:
      - task: check
    cmds:
      - task: service
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/qbittorrent.yml

  qbittorrent:up:
    desc: run service qbittorrent
    run: once
    deps:
      - task: check
    cmds:
      - task: up
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/qbittorrent.yml

  qbittorrent:down:
    desc: down service qbittorrent
    run: once
    deps:
      - task: check
    cmds:
      - task: down
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/qbittorrent.yml

  jellyfin:
    desc: run service jellyfin
    run: once
    deps:
      - task: check
    cmds:
      - task: service
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/jellyfin.yml

  jellyfin:up:
    desc: run service jellyfin
    run: once
    deps:
      - task: check
    cmds:
      - task: up
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/jellyfin.yml

  jellyfin:down:
    desc: down service jellyfin
    run: once
    deps:
      - task: check
    cmds:
      - task: down
        vars:
          COMPOSE_SERVICE_FILE: provision/compose/jellyfin.yml
