- name: Common stuff for all the server
  hosts: all
  become: true
  gather_facts: true
  roles:
    - contrib/hadenlabs.authorization
    - contrib/hadenlabs.common
    - contrib/hadenlabs.docker
  tags:
    - all
    - common
    - provision
    - sync
