- name: load vars encrypteds
  hosts: all
  tasks:
    - name: Load encrypted vars file
      community.sops.load_vars:
        file: vars/all.sops.yml
  tags:
    - common
    - configuration

- name: Common stuff for all the server
  hosts: all
  become: true
  gather_facts: true
  roles:
    - contrib/hadenlabs.authorization
    - contrib/hadenlabs.common
    - contrib/hadenlabs.docker
  tags:
    - all
    - common
    - provision
    - sync

- name: Install or upgrade docker
  hosts: all
  become: true
  gather_facts: true
  roles:
    - contrib/hadenlabs.docker
  tags:
    - docker

- name: install openssl
  hosts: all
  become: true
  gather_facts: true
  roles:
    - contrib/hadenlabs.openssl
  tags:
    - provision
    - openssl

- name: Deploy configuration for all the server
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: contrib/hadenlabs.common
      vars:
        common_only_deploy: yes
  tags:
    - deploy
    - sync
