---
common_user: '{{ user }}'

authorization_user: '{{ user }}'
authorization_key_public: '~/.ssh/id_rsa.pub'
authorization_key_private: '~/.ssh/id_rsa'

common_packages:
  - 'vim'
  - 'git'

docker_users:
  - '{{ user }}'

common_create_files:
  - path: '/home/{{ user }}/home-automation/.env'
    owner: '{{ user }}'
    mode: '0775'

common_create_directories:
  - path: '/media/eviljasperdisk/appdata'
    owner: '{{ user }}'
    mode: '0775'
  - path: '/media/eviljasperdisk/data'
    owner: '{{ user }}'
    mode: '0775'
  - path: '/media/eviljasperdisk/downloads'
    owner: '{{ user }}'
    mode: '0775'
  - path: '/media/eviljasperdisk/media'
    owner: '{{ user }}'
    mode: '0775'
  - path: '/media/eviljasperdisk/restick'
    owner: '{{ user }}'
    mode: '0775'
  - path: '/media/eviljasperdisk/restick/data'
    owner: '{{ user }}'
    mode: '0775'

common_environment_dict:
  path: '/home/{{ user }}/home-automation/.env'
  owner: '{{ user }}'
  group: '{{ user }}'
  permissions: '0755'
  envs:
    APP_NAME: home-automation
    APPDATA_PATH: /media/eviljasperdisk/appdata
    DATA_PATH: /media/eviljasperdisk/data
    RESTIC_DATA_PATH: /media/eviljasperdisk/restick/data
    DOWNLOAD_PATH: /media/eviljasperdisk/downloads
    MEDIA_PATH: /media/eviljasperdisk/media
    TIMEZONE: America/Lima
    PUID: 1000
    PGID: 1000
    PIHOLE_PASSWORD: '{{ pihole_password }}'
    PIHOLE_IP: '{{ pihole_ip }}'

common_deployments:
  - name: 'home-automation'
    version: 'develop' # Could be a hash, branch or tag name
    repo: 'git@github.com:luismayta/home-automation.git'
    force: yes
    location: '/home/{{ user }}/home-automation'
